#!/usr/bin/env python
"""Build publisher-compatible overall comparison figures for the paper.

The figures use ``table_literature_comparison_common46.csv`` generated by
``build_paper_tables.py``.  MAE therefore follows the MSCMNet supplementary
publisher convention (sum of DMA-level MAEs), while MAPE/RMSE/NSE are metrics
on the hourly aggregate-demand series.  This script intentionally overwrites
only ``test_overall_24h.*`` and ``test_overall_168h.*``; ablation, day-wise,
DMA-level, and Pearson figures keep their own scientifically appropriate
aggregate-demand / DMA-level conventions.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


METRICS = ("MAE", "MAPE", "RMSE", "NSE")
EXPECTED_MODELS = (
    "GRU (reported)",
    "LSTM (reported)",
    "MSNet (reported)",
    "MSCMNet_WM (reported)",
    "MSCMNet_M (reported)",
    "MSCMNet_W (reported)",
    "DCRNN",
    "STGCN",
    "STaR-GNN",
)


def _validate(frame: pd.DataFrame) -> None:
    required = {"task", "model", *METRICS}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Literature table missing columns: {sorted(missing)}")
    for task in ("24h", "168h"):
        models = tuple(frame.loc[frame["task"] == task, "model"].astype(str))
        if models != EXPECTED_MODELS:
            raise ValueError(f"Unexpected model order for {task}: {models}")
        if not np.isfinite(frame.loc[frame["task"] == task, list(METRICS)].to_numpy(float)).all():
            raise ValueError(f"Non-finite metrics in literature table for {task}")


def _save(fig: plt.Figure, base: Path) -> None:
    fig.tight_layout()
    fig.savefig(base.with_suffix(".png"), dpi=300, bbox_inches="tight")
    fig.savefig(base.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def _plot_task(frame: pd.DataFrame, task: str, figure_dir: Path) -> None:
    selected = frame.loc[frame["task"] == task].copy()
    labels = [name.replace(" (reported)", "") for name in selected["model"].astype(str)]
    x = np.arange(len(labels))

    fig, axes = plt.subplots(2, 2, figsize=(13.0, 8.5))
    for axis, metric in zip(axes.ravel(), METRICS):
        values = selected[metric].to_numpy(float)
        bars = axis.bar(x, values, edgecolor="black", linewidth=0.45)
        for bar, model in zip(bars, selected["model"].astype(str)):
            if model == "STaR-GNN":
                bar.set_hatch("//")
                bar.set_linewidth(1.2)
        axis.set_xticks(x, labels, rotation=35, ha="right")
        axis.set_ylabel(metric + (" (%)" if metric == "MAPE" else ""))
        axis.set_title(
            metric + (" (higher is better)" if metric == "NSE" else " (lower is better)")
        )
        axis.grid(axis="y", alpha=0.25)

    fig.suptitle(
        f"Publisher-compatible literature comparison ({task})",
        fontsize=14,
    )
    _save(fig, figure_dir / f"test_overall_{task}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--table",
        type=Path,
        default=Path("paper/tables/literature/table_literature_comparison_common46.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/figures"),
    )
    args = parser.parse_args()

    table = args.table.resolve()
    output = args.output.resolve()
    if not table.is_file():
        raise FileNotFoundError(
            f"Literature comparison table not found: {table}. "
            "Run build_paper_tables.py first."
        )
    output.mkdir(parents=True, exist_ok=True)

    frame = pd.read_csv(table)
    _validate(frame)
    for task in ("24h", "168h"):
        _plot_task(frame, task, output)

    print(f"Literature figures: {output}")
    print("Publisher-compatible figure audit: PASS")


if __name__ == "__main__":
    main()
